# Generated by Django 5.1.7 on 2025-03-19 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='id',
        ),
        migrations.AddField(
            model_name='filme',
            name='id_fime',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
