# Generated by Django 5.1.7 on 2025-03-19 13:13

import filmes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_remove_filme_id_filme_id_fime'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=filmes.models.upload_image),
        ),
    ]
