# Generated by Django 5.1.7 on 2025-03-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filme_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='id_fime',
            new_name='id_filme',
        ),
    ]
